helmDefaults:
    timeout: 600
    skipDeps: true
    historyMax: 2
    kubeContext: minikube
missingFileHandler: Error

repositories:

releases:
- name: redis
  chart: ./Charts/Redis
  namespace: redis
  values:
  - config: {}
