apiVersion: v1
kind: Config
clusters:
- cluster:
    server: host_ip:8001
  name: minikube
contexts:
- context:
    cluster: minikube
    user: default
  name: minikube
current-context: minikube
users:
- name: default
  user: {}
