apiVersion: v1
kind: Service
metadata:
    name: {{ include "common.names.name" . }}
    namespace: {{ .Release.Name }}
    labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
    type: ClusterIP
    sessionAffinity: None
    publishNotReadyAddresses: false
    selector:
        {{- include "common.labels.matchLabels" . | nindent 6 }}
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}