apiVersion: v1
kind: Service
metadata:
    name: {{ include "common.names.name" . }}
    namespace: {{ .Release.Name }}
    labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
    type: NodePort
    selector:
        app: {{ .Release.Name }}
        name: {{ .Release.Name }}
    ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.externalPort }}
    sessionAffinity: None
    externalTrafficPolicy: Cluster