apiVersion: v1
kind: Service
metadata:
    name: {{ include "common.names.name" . }}
    namespace: {{ .Release.Name }}
    labels: {{- include "common.labels.standard" . | nindent 6 }}
spec:
    type: NodePort
    selector: {{- include "common.labels.matchLabels" . | nindent 6}}
    ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.externalPort }}
    sessionAffinity: None
    externalTrafficPolicy: Cluster