name: Alarm Workflow File

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Alarm Bash
        run: ./Alarm++.sh
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Run Alarm Python
        run: python3 Alarm++.py
  
