name: Test Alarm Package

on:
  push:
    branches:
      - testing-branch

jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Local Package
        run: |
            cd Packages/WebsiteWatcher
            pip install .
      - name: Run pytest
        run: pytest
  